# Generated by Django 5.1.1 on 2025-10-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Nivel de severidad de la alerta.', max_length=10)),
                ('unit', models.CharField(default='kWh', help_text='Unidad por defecto (kWh, W, A, etc.).', max_length=32)),
                ('default_min_threshold', models.FloatField(blank=True, help_text='Umbral mínimo por defecto.', null=True)),
                ('default_max_threshold', models.FloatField(blank=True, help_text='Umbral máximo por defecto.', null=True)),
            ],
            options={
                'db_table': 'alert_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.IntegerField(blank=True, help_text='Power in Watts', null=True)),
                ('max_consumption', models.IntegerField(help_text='Maximum allowed consumption in kWh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dispositivos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('alert_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(help_text='Consumption in kWh')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(help_text='Código único de inventario (SKU).', max_length=80, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('nominal_voltage_v', models.FloatField(blank=True, null=True)),
                ('max_current_a', models.FloatField(blank=True, null=True)),
                ('standby_power_w', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Categoría del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dispositivos.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('min_threshold', models.FloatField(blank=True, help_text='Umbral mínimo (override).', null=True)),
                ('max_threshold', models.FloatField(blank=True, help_text='Umbral máximo (override).', null=True)),
                ('unit_override', models.CharField(blank=True, help_text='Unidad específica (opcional).', max_length=32, null=True)),
                ('alert_rule', models.ForeignKey(help_text='Regla de alerta aplicada a este producto.', on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='dispositivos.alertrule')),
                ('product', models.ForeignKey(help_text='Producto al que se aplica la alerta con umbrales específicos.', on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='dispositivos.product')),
            ],
            options={
                'db_table': 'product_alert_rule',
                'ordering': ['product_id', 'alert_rule_id'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Productos a los que aplica esta regla (relación N:M con umbrales por producto).', related_name='alert_rules', through='dispositivos.ProductAlertRule', to='dispositivos.product'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.zone'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_afe0af_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product'], name='product_ale_product_01a756_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['alert_rule'], name='product_ale_alert_r_acd589_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product', 'alert_rule'], name='product_ale_product_fca7e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.UniqueConstraint(fields=('product', 'alert_rule'), name='uix_product_alert_unique'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_threshold__isnull', True), ('max_threshold__isnull', True), ('min_threshold__lte', models.F('max_threshold')), _connector='OR'), name='par_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['severity'], name='alert_rule_severit_cc978d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['name'], name='alert_rule_name_3749b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.CheckConstraint(condition=models.Q(('default_min_threshold__isnull', True), ('default_max_threshold__isnull', True), ('default_min_threshold__lte', models.F('default_max_threshold')), _connector='OR'), name='alert_rule_default_min_lte_max'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('name', 'severity')},
        ),
    ]
