# Generated by Django 5.1.1 on 2025-11-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
