# Generated by Django 5.1.1 on 2025-09-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_category_organization_remove_dispositivo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos/'),
        ),
    ]
