# Generated by Django 5.1.1 on 2025-09-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
