# Generated by Django 5.1.1 on 2025-11-10 00:27

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path),
        ),
    ]
