# Generated by Django 5.1.1 on 2025-10-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
